export default {
    SET_GENRES: 'SET_GENRES',
    SET_ACTIVE_MOVIE: 'SET_ACTIVE_MOVIE',
    UPDATE_MOVIE_DATA: 'UPDATE_MOVIE_DATA',
    ADD_TO_WATCHLIST: 'ADD_TO_WATCHLIST',
    REMOVE_FROM_WATCHLIST: 'REMOVE_FROM_WATCHLIST',
};